In [2]:
import numpy as np
import pandas as pd
import pickle
import warnings
warnings.filterwarnings('ignore')

In [3]:
pipe = pickle.load(open('./models/model_pkl','rb'))

In [76]:
# Assume user input
test_input = np.array([0,1, 0, 0, 0,0, 0, 1, 'radio', 'fwdbtn', 'trackdone'],dtype=object).reshape(1,11)

test_input3 = np.array([0, 1, 0, 0, 0, 0, 1, 1, 'editorial_playlist', 'fwdbtn', 'fwdbtn'],dtype=object).reshape(1,11)

test_input2 = np.array([0,1, 0, 0, 0,0, 0, 1, 4,4,6],dtype=object).reshape(1,11)

test_input2

array([[0, 1, 0, 0, 0, 0, 0, 1, 4, 4, 6]], dtype=object)

In [77]:
pipe.predict(test_input3)

array([1])

In [24]:
pipe2.predict(test_input2)

array([0])

### Loading a test data

In [36]:
df_logs_mod_final = pd.read_csv('model.csv')

In [37]:
df_logs_mod_final.shape

(159445, 13)

In [38]:
df_logs_mod_final

track_id  target  context_switch  \
0       t_0479f24c-27d2-46d6-a00c-7ec928f2b539       0               0   
1       t_9099cd7b-c238-47b7-9381-f23f2c1d1043       0               0   
2       t_fc5df5ba-5396-49a7-8b29-35d0d28249e0       0               0   
3       t_23cff8d6-d874-4b20-83dc-94e450e8aa20       0               0   
4       t_64f3743c-f624-46bb-a579-0f3f9a07a123       0               0   
...                                        ...     ...             ...   
159440  t_360910e8-2a84-42b0-baf1-59abcf96a1f2       0               0   
159441  t_aa2fff77-9b0a-4fa3-a685-ecef50310e8a       0               0   
159442  t_f673e1b7-4ebe-4fc1-ac24-a9f25de70381       0               0   
159443  t_e172e8e7-7161-42a9-acb0-d606346c8f87       0               0   
159444  t_77977dd6-597e-4425-8f8f-4efb32ecfba6       0               0   

        no_pause_before_play  short_pause_before_play  long_pause_before_play  \
0                          0                        0                       0   
1                          1                        0                       0   
2                          1                        0                       0   
3                          1                        0                       0   
4                          1                        0                       0   
...                      ...                      ...                     ...   
159440                     1                        0                       0   
159441                     1                        0                       0   
159442                     1                        0                       0   
159443                     1                        0                       0   
159444                     1                        0                       0   

        hist_user_behavior_n_seekfwd  hist_user_behavior_n_seekback  \
0                                  0                              0   
1                                  0                              0   
2                                  0                              0   
3                                  0                              0   
4                                  0                              0   
...                              ...                            ...   
159440                             0                              0   
159441                             0                              0   
159442                             0                              0   
159443                             0                              0   
159444                             0                              0   

        hist_user_behavior_is_shuffle  premium        context_type  \
0                                   1        1  editorial_playlist   
1                                   1        1  editorial_playlist   
2                                   1        1  editorial_playlist   
3                                   1        1  editorial_playlist   
4                                   1        1  editorial_playlist   
...                               ...      ...                 ...   
159440                              0        1     user_collection   
159441                              0        1     user_collection   
159442                              0        1     user_collection   
159443                              0        1     user_collection   
159444                              0        1     user_collection   

       hist_user_behavior_reason_start hist_user_behavior_reason_end  
0                            trackdone                     trackdone  
1                            trackdone                     trackdone  
2                            trackdone                     trackdone  
3                            trackdone                     trackdone  
4                            trackdone                     trackdone  
...                                ...                  

In [42]:
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [40]:
X_final = df_logs_mod_final.drop(['track_id','target'], axis= 1)
y_final = df_logs_mod_final['target']


#splot
X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(X_final, y_final, test_size=0.3, random_state=17)

print("The dimension of X_train_final is {}".format(X_train_final.shape))
print("The dimension of X_test_final is {}".format(X_test_final.shape))

The dimension of X_train_final is (111611, 11)
The dimension of X_test_final is (47834, 11)


In [59]:
X_train_final

context_switch  no_pause_before_play  short_pause_before_play  \
30745                0                     1                        0   
101187               0                     1                        0   
129730               0                     1                        0   
50296                0                     1                        0   
33083                0                     0                        1   
...                ...                   ...                      ...   
25631                0                     1                        0   
125680               0                     0                        1   
42297                0                     1                        0   
34959                0                     0                        1   
64753                0                     1                        0   

        long_pause_before_play  hist_user_behavior_n_seekfwd  \
30745                        0                             0   
101187                       0                             0   
129730                       0                             0   
50296                        0                             0   
33083                        1                             0   
...                        ...                           ...   
25631                        0                             0   
125680                       1                             0   
42297                        0                             0   
34959                        1                             0   
64753                        0                             0   

        hist_user_behavior_n_seekback  hist_user_behavior_is_shuffle  premium  \
30745                               0                              0        1   
101187                              0                              0        1   
129730                              0                              0        1   
50296                               0                              0        1   
33083                               0                              0        1   
...                               ...                            ...      ...   
25631                               0                              0        1   
125680                              0                              0        0   
42297                               0                              1        1   
34959                               0                              0        0   
64753                               0                              1        1   

              context_type hist_user_behavior_reason_start  \
30745                radio                          fwdbtn   
101187     user_collection                       trackdone   
129730             catalog                       trackdone   
50296      user_collection                          fwdbtn   
33083   editorial_playlist                       trackdone   
...                    ...                             ...   
25631              catalog                       trackdone   
125680  editorial_playlist                        clickrow   
42297      user_collection                          fwdbtn   
34959                radio                          fwdbtn   
64753   editorial_playlist                          fwdbtn   

       hist_user_behavior_reason_end  
30745                      trackdone  
101187                     trackdone  
129730                     trackdone  
50296                      trackdone  
33083                      trackdone  
...                              ...  
25631                      trackdone  
125680                     trackdone  
42297                         fwdbtn  
34959                         fwdbtn  
64753                         fwdbtn  

[111611 rows x 11 columns]

In [60]:
# cols = ['context_type','hist_user_behavior_reason_start','hist_user_behavior_reason_end']

# Encoding
trf1 = ColumnTransformer([
    ('encode',OneHotEncoder(sparse=False,handle_unknown='ignore'),[8,9,10])
    ],remainder='passthrough')

# train the model
trf2 = RandomForestClassifier()

In [61]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2)
])

In [62]:
# train
pipe.fit(X_train_final,y_train_final)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('encode',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  [8, 9, 10])])),
                ('trf2', RandomForestClassifier())])

In [63]:
# Predict
y_pred = pipe.predict(X_test_final)

y_pred

array([1, 0, 0, ..., 1, 1, 0])

In [64]:
pipe.predict(test_input2)

array([1])

In [78]:
df_logs_mod_final[df_logs_mod_final['target'] == 1].iloc[:1,:]

track_id  target  context_switch  \
6  t_e23c19f5-4c32-4557-aa44-81372c2e3705       1               0   

   no_pause_before_play  short_pause_before_play  long_pause_before_play  \
6                     1                        0                       0   

   hist_user_behavior_n_seekfwd  hist_user_behavior_n_seekback  \
6                             0                              0   

   hist_user_behavior_is_shuffle  premium        context_type  \
6                              1        1  editorial_playlist   

  hist_user_behavior_reason_start hist_user_behavior_reason_end  
6                          fwdbtn                        fwdbtn

In [79]:
arr = [1]

In [80]:
arr[0] == 1

1